version: '3'
services:
  # web:
  #  image: "lectures"
  #  ports:
  #   - "5051:5051"
  db:
    image: "skalera/postgres:latest"
    ports:
      - "5433:5432" # visible at 5433
    environment:
      POSTGRES_USER: "irrogation"
      POSTGRES_PASSWORD: "irrogation"
      POSTGRES_DB: "irrogation"